// Generated by tooling/brand-gen.mjs from brand/hjal/tokens.json. Do not edit;
// run `pnpm brand:gen`.

package samtak.spjall.brand

object BrandTokens {
    /** sRGB as 0xAARRGGBB, for `androidx.compose.ui.graphics.Color(Long)`. */
    object Colors {
        /** Cream band and the other party's bubble. */
        const val BG: Long = 0xFFFDE9D7L
        /** Screen background. */
        const val SURFACE: Long = 0xFFFFFFFFL
        /** Text on light, black-green. */
        const val FG: Long = 0xFF071307L
        /** Brick red: main action, own bubble. */
        const val PRIMARY: Long = 0xFFB31800L
        const val PRIMARY_FG: Long = 0xFFFFFFFFL
        /** Gold: accents and rules. Decorative; see verified-mark for the meaning-bearing gold. */
        const val SECONDARY: Long = 0xFFEDA33BL
        const val SECONDARY_FG: Long = 0xFF071307L
        const val PROSE_BODY: Long = 0xFF1E293BL
        const val MUTED: Long = 0xFFECE3DAL
        const val MUTED_FG: Long = 0xFF59677DL
        /** Decorative dividers only. */
        const val BORDER: Long = 0x2E071307L
        /** Boundaries that identify a control. */
        const val BORDER_STRONG: Long = 0x80071307L
        const val DANGER: Long = 0xFFB31800L
        const val DANGER_FG: Long = 0xFFFFFFFFL
        const val SUCCESS: Long = 0xFF19946CL
        const val WARNING: Long = 0xFFFF7F25L
        const val WARNING_FG: Long = 0xFF071307L
        const val INFO: Long = 0xFF2184D1L
        const val SUCCESS_TEXT: Long = 0xFF00754FL
        const val WARNING_TEXT: Long = 0xFFB22D00L
        const val INFO_TEXT: Long = 0xFF0066B1L
        const val BUBBLE_OWN_BG: Long = 0xFFB31800L
        const val BUBBLE_OWN_FG: Long = 0xFFFFFFFFL
        const val BUBBLE_OTHER_BG: Long = 0xFFFDE9D7L
        const val BUBBLE_OTHER_FG: Long = 0xFF071307L
        /** The verification dot. Same hue and chroma as secondary, lightness lowered until it meets the 3:1 non-text threshold (WCAG 1.4.11) on surface and bg, because the dot carries meaning. */
        const val VERIFIED_MARK: Long = 0xFFB46E00L
    }

    /** Font family names; the font files are bundled by the app. */
    object Fonts {
        const val SANS: String = "Gothic A1"
        const val HEADLINE: String = "Archivo Condensed"
    }

    object Radius {
        const val MD_DP: Int = 6
    }
}
