// Generated by tooling/brand-gen.mjs from brand/hjal/strings.is.json. Do not edit;
// run `pnpm brand:gen`.

export const brandStrings = {
  /** Launcher label, home-screen name, store-facing display name. */
  app_name: "Hjal",
  /** APNs alert text shown when the notification service extension cannot decrypt in time. Never names the sender. */
  push_fallback_body: "Ný skilaboð á Hjal",
  /** The only permitted statement about where data lives (docs/decisions/0001). */
  residency_claim: "Gögnin eru geymd varanlega innan ESB; unnin á netkerfi Cloudflare.",
} as const;
