// @ts-check
// Android outputs of the brand: string resources, the token object and the
// adaptive launcher icon, all in the `core/brand` module.

import { brandColors, fontFamilies, hex2, radii } from "./color.mjs";
import { renderPng } from "./icon.mjs";
import { keysFor, positional } from "./strings.mjs";

/**
 * @typedef {import("./strings.mjs").BrandInput} BrandInput
 * @typedef {import("./strings.mjs").OutputFile} OutputFile
 */

const RES = "android/core/brand/src/main/res";
const KOTLIN = "android/core/brand/src/main/kotlin/samtak/spjall/brand/BrandTokens.kt";

/** Launcher foreground per density: the 108 dp adaptive-icon canvas. */
const DENSITIES = /** @type {const} */ ([
  ["mdpi", 108],
  ["hdpi", 162],
  ["xhdpi", 216],
  ["xxhdpi", 324],
  ["xxxhdpi", 432],
]);

/**
 * A string resource value: XML-escaped, then Android's own escapes (aapt2
 * treats `'` and `"` as syntax and a leading `@` or `?` as a reference).
 *
 * @param {string} text
 */
export function androidEscape(text) {
  const out = text
    .replaceAll("\\", "\\\\")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll("'", "\\'")
    .replaceAll('"', '\\"')
    .replaceAll("\n", "\\n");
  return /^[@?]/.test(out) ? `\\${out}` : out;
}

/** @param {string} text */
function xmlComment(text) {
  return `<!-- ${text.replaceAll("--", "- -")} -->`;
}

/**
 * @param {number} position
 * @param {string} type
 */
function specifier(position, type) {
  return `%${position}$${type === "int" ? "d" : "s"}`;
}

/** @param {BrandInput} brand */
function stringsXml(brand) {
  const lines = [
    '<?xml version="1.0" encoding="utf-8"?>',
    xmlComment(
      `Generated by tooling/brand-gen.mjs from brand/${brand.name}/. Do not edit; run pnpm brand:gen.`,
    ),
    "<resources>",
  ];
  for (const [key, spec] of keysFor(brand.contract, "android")) {
    const value = brand.strings[key];
    lines.push(`    ${xmlComment(spec.description)}`);
    if (typeof value === "string") {
      const text = androidEscape(positional(value, spec, specifier));
      lines.push(`    <string name="${key}">${text}</string>`);
      continue;
    }
    lines.push(`    <plurals name="${key}">`);
    for (const [quantity, text] of Object.entries(value ?? {})) {
      const item = androidEscape(positional(text, spec, specifier));
      lines.push(`        <item quantity="${quantity}">${item}</item>`);
    }
    lines.push("    </plurals>");
  }
  lines.push("</resources>", "");
  return lines.join("\n");
}

/** @param {string} name */
function constName(name) {
  return name.toUpperCase().replaceAll("-", "_");
}

/** @param {BrandInput} brand */
function tokensKotlin(brand) {
  /** @param {string | undefined} text */
  const doc = (text) => (text ? [`        /** ${text} */`] : []);
  const colors = brandColors(brand.tokens).flatMap((c) => [
    ...doc(c.description),
    `        const val ${constName(c.name)}: Long = 0x${hex2(c.a)}${hex2(c.r)}${hex2(c.g)}${hex2(c.b)}L`,
  ]);
  const fonts = fontFamilies(brand.tokens).map(
    (f) => `        const val ${constName(f.name)}: String = "${f.family}"`,
  );
  const radius = radii(brand.tokens).map(
    (r) => `        const val ${constName(r.name)}_DP: Int = ${r.value}`,
  );
  return [
    `// Generated by tooling/brand-gen.mjs from brand/${brand.name}/tokens.json. Do not edit;`,
    "// run `pnpm brand:gen`.",
    "",
    "package samtak.spjall.brand",
    "",
    "object BrandTokens {",
    "    /** sRGB as 0xAARRGGBB, for `androidx.compose.ui.graphics.Color(Long)`. */",
    "    object Colors {",
    ...colors,
    "    }",
    "",
    "    /** Font family names; the font files are bundled by the app. */",
    "    object Fonts {",
    ...fonts,
    "    }",
    "",
    "    object Radius {",
    ...radius,
    "    }",
    "}",
    "",
  ].join("\n");
}

/** @param {BrandInput} brand */
function launcherIcon(brand) {
  const { r, g, b } = brandColors(brand.tokens).find(
    (c) => c.name === brand.manifest.icon.background,
  ) ?? { r: 0, g: 0, b: 0 };
  const adaptive = [
    '<?xml version="1.0" encoding="utf-8"?>',
    xmlComment("Generated by tooling/brand-gen.mjs. Do not edit."),
    '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">',
    '    <background android:drawable="@color/ic_launcher_background" />',
    '    <foreground android:drawable="@mipmap/ic_launcher_foreground" />',
    '    <monochrome android:drawable="@mipmap/ic_launcher_foreground" />',
    "</adaptive-icon>",
    "",
  ].join("\n");
  /** @type {OutputFile[]} */
  const files = [
    { path: `${RES}/mipmap-anydpi/ic_launcher.xml`, content: adaptive },
    { path: `${RES}/mipmap-anydpi/ic_launcher_round.xml`, content: adaptive },
    {
      path: `${RES}/values/ic_launcher_background.xml`,
      content: [
        '<?xml version="1.0" encoding="utf-8"?>',
        xmlComment("Generated by tooling/brand-gen.mjs. Do not edit."),
        "<resources>",
        `    <color name="ic_launcher_background">#${hex2(r)}${hex2(g)}${hex2(b)}</color>`,
        "</resources>",
        "",
      ].join("\n"),
    },
  ];
  for (const [density, size] of DENSITIES) {
    files.push({
      path: `${RES}/mipmap-${density}/ic_launcher_foreground.png`,
      content: renderPng(brand.iconSvg, size),
    });
  }
  return files;
}

/**
 * @param {BrandInput} brand
 * @returns {OutputFile[]}
 */
export function android(brand) {
  return [
    { path: `${RES}/values/strings.xml`, content: stringsXml(brand) },
    { path: KOTLIN, content: tokensKotlin(brand) },
    ...launcherIcon(brand),
  ];
}
