// @ts-check
// The backend's few brand strings (the push fallback, the residency claim),
// as a typed constant the Worker imports.

import { keysFor } from "./strings.mjs";

/**
 * @typedef {import("./strings.mjs").BrandInput} BrandInput
 * @typedef {import("./strings.mjs").OutputFile} OutputFile
 */

/**
 * @param {BrandInput} brand
 * @returns {OutputFile[]}
 */
export function backend(brand) {
  const entries = keysFor(brand.contract, "backend").map(
    ([key, spec]) =>
      `  /** ${spec.description} */\n  ${key}: ${JSON.stringify(brand.strings[key])},`,
  );
  const content = [
    `// Generated by tooling/brand-gen.mjs from brand/${brand.name}/strings.is.json. Do not edit;`,
    "// run `pnpm brand:gen`.",
    "",
    "export const brandStrings = {",
    ...entries,
    "} as const;",
    "",
  ].join("\n");
  return [{ path: "backend/src/brand.gen.ts", content }];
}
