// @ts-check
// iOS outputs of the brand, all under ios/Generated/: the xcconfigs the
// project includes, the string catalog, the token enum and the app icon.

import { brandColors, fontFamilies, hex2, radii } from "./color.mjs";
import { renderOpaquePng } from "./icon.mjs";
import { camel, keysFor, positional } from "./strings.mjs";

/**
 * @typedef {import("./strings.mjs").BrandInput} BrandInput
 * @typedef {import("./strings.mjs").OutputFile} OutputFile
 */

const DIR = "ios/Generated";
const XCODE_INFO = { author: "xcode", version: 1 };

/**
 * @param {number} position
 * @param {string} type
 */
function specifier(position, type) {
  return `%${position}$${type === "int" ? "lld" : "@"}`;
}

/** @param {unknown} value */
function json(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

/** @param {BrandInput} brand */
function xcconfig(brand) {
  const hosts = [brand.ids.hosts.link, ...brand.manifest.aliasHosts];
  return [
    `// Generated by tooling/brand-gen.mjs from brand/${brand.name}/. Do not edit; run`,
    "// `pnpm brand:gen`. No DEVELOPMENT_TEAM here: the team is a frozen id",
    "// (identifiers/ids.json), not part of the brand.",
    "",
    `INFOPLIST_KEY_CFBundleDisplayName = ${brand.manifest.displayName}`,
    "ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon",
    `BRAND_ASSOCIATED_DOMAINS = ${hosts.map((h) => `applinks:${h}`).join(" ")}`,
    "",
  ].join("\n");
}

/**
 * The frozen ids Xcode needs, so project.yml names none of them. Not brand
 * data, but generated here so the same --check holds it to ids.json. A null
 * Apple team (decision 0010) leaves DEVELOPMENT_TEAM empty: debug builds run
 * unsigned and a release build cannot be signed.
 *
 * @param {BrandInput} brand
 */
function idsXcconfig(brand) {
  const { store, hosts, services } = brand.ids;
  return [
    "// Generated by tooling/brand-gen.mjs from identifiers/ids.json. Do not edit;",
    "// run `pnpm brand:gen`.",
    "",
    `SPJALL_BUNDLE_ID = ${store.iosBundleId}`,
    `SPJALL_NSE_BUNDLE_ID = ${store.iosNotificationServiceBundleId}`,
    `SPJALL_APP_GROUP = ${store.appGroup}`,
    `SPJALL_URL_SCHEME = ${store.urlScheme}`,
    `SPJALL_API_HOST = ${hosts.api}`,
    `DEVELOPMENT_TEAM = ${services.appleTeamId ?? ""}`,
    "",
  ].join("\n");
}

/** @param {BrandInput} brand */
function stringCatalog(brand) {
  /** @type {Record<string, unknown>} */
  const strings = {};
  for (const [key, spec] of keysFor(brand.contract, "ios")) {
    const value = brand.strings[key];
    /** @param {string} text */
    const unit = (text) => ({
      stringUnit: { state: "translated", value: positional(text, spec, specifier) },
    });
    const localization =
      typeof value === "string"
        ? unit(value)
        : {
            variations: {
              plural: Object.fromEntries(
                Object.entries(value ?? {}).map(([category, text]) => [category, unit(text)]),
              ),
            },
          };
    strings[key] = {
      comment: spec.description,
      extractionState: "manual",
      localizations: { is: localization },
    };
  }
  return json({ sourceLanguage: "is", strings, version: "1.0" });
}

/** @param {BrandInput} brand */
function tokensSwift(brand) {
  /** @param {string | undefined} text */
  const doc = (text) => (text ? [`        /// ${text}`] : []);
  const colors = brandColors(brand.tokens).flatMap((c) => [
    ...doc(c.description),
    `        static let ${camel(c.name)} = Color(.sRGB, red: ${c.r} / 255, green: ${c.g} / 255, blue: ${c.b} / 255, opacity: ${c.a} / 255) // #${hex2(c.r)}${hex2(c.g)}${hex2(c.b)}${c.a < 255 ? hex2(c.a) : ""}`,
  ]);
  const fonts = fontFamilies(brand.tokens).map(
    (f) => `        static let ${camel(f.name)} = "${f.family}"`,
  );
  const radius = radii(brand.tokens).map(
    (r) => `        static let ${camel(r.name)}: CGFloat = ${r.value}`,
  );
  return [
    `// Generated by tooling/brand-gen.mjs from brand/${brand.name}/tokens.json. Do not edit;`,
    "// run `pnpm brand:gen`.",
    "",
    "import SwiftUI",
    "",
    "enum BrandTokens {",
    "    enum Colors {",
    ...colors,
    "    }",
    "",
    "    /// Font family names; the font files are bundled by the app.",
    "    enum Fonts {",
    ...fonts,
    "    }",
    "",
    "    enum Radius {",
    ...radius,
    "    }",
    "}",
    "",
  ].join("\n");
}

/**
 * The foreground framed for iOS. Android masks the 108 canvas down to the
 * central 66 and adds its own margin; iOS shows the square as it is, so the
 * 66 safe zone gets a 6-unit margin on each side instead.
 *
 * @param {string} svg
 */
function iosFrame(svg) {
  const canvas = 'viewBox="0 0 108 108"';
  if (!svg.includes(canvas)) throw new Error(`icon foreground must use ${canvas}`);
  return svg.replace(canvas, 'viewBox="15 15 78 78"');
}

/** @param {BrandInput} brand */
function appIcon(brand) {
  const color = brandColors(brand.tokens).find((c) => c.name === brand.manifest.icon.background);
  const background = color ? `#${hex2(color.r)}${hex2(color.g)}${hex2(color.b)}` : "#000000";
  const set = `${DIR}/Assets.xcassets/AppIcon.appiconset`;
  return [
    { path: `${DIR}/Assets.xcassets/Contents.json`, content: json({ info: XCODE_INFO }) },
    {
      path: `${set}/Contents.json`,
      content: json({
        images: [
          {
            filename: "AppIcon-1024.png",
            idiom: "universal",
            platform: "ios",
            size: "1024x1024",
          },
        ],
        info: XCODE_INFO,
      }),
    },
    {
      path: `${set}/AppIcon-1024.png`,
      content: renderOpaquePng(iosFrame(brand.iconSvg), 1024, background),
    },
  ];
}

/**
 * @param {BrandInput} brand
 * @returns {OutputFile[]}
 */
export function ios(brand) {
  return [
    { path: `${DIR}/Brand.xcconfig`, content: xcconfig(brand) },
    { path: `${DIR}/Ids.xcconfig`, content: idsXcconfig(brand) },
    { path: `${DIR}/Localizable.xcstrings`, content: stringCatalog(brand) },
    { path: `${DIR}/BrandTokens.swift`, content: tokensSwift(brand) },
    ...appIcon(brand),
  ];
}
