// Generated by tooling/ws-kotlin.mjs from api/openapi.json. Do not edit; run
// `node tooling/ws-kotlin.mjs` after `pnpm --filter spjall-backend openapi`.

package samtak.spjall.api

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Every frame on the WebSocket, tagged by `type` */
@Serializable
sealed interface WsFrame

/** Server to client, first frame on a new socket */
@Serializable
@SerialName("hello")
data class HelloFrame(
    /** Protocol version the server speaks */
    val protocol: Long,
    val serverTime: String,
) : WsFrame

/** Server to client: a conversation has messages up to `seq`; fetch them */
@Serializable
@SerialName("notify")
data class NotifyFrame(
    val conversationId: String,
    /** The newest sequence number in the conversation */
    val seq: Long,
) : WsFrame

/** Client to server: moves this device's delivery cursor */
@Serializable
@SerialName("ack")
data class AckFrame(
    val conversationId: String,
    /** This device has stored everything up to here */
    val seq: Long,
) : WsFrame

/** Either direction: an encrypted typing indicator, relayed and never stored */
@Serializable
@SerialName("typing")
data class TypingFrame(
    val conversationId: String,
    /** An envelope of kind typing, sealed under a key exported from the current epoch (not an MLS message) */
    val ciphertext: String,
) : WsFrame

/** Either direction; answered with `pong` */
@Serializable
@SerialName("ping")
data class PingFrame(
    val nonce: String? = null,
) : WsFrame

/** The answer to `ping`, echoing its nonce */
@Serializable
@SerialName("pong")
data class PongFrame(
    val nonce: String? = null,
) : WsFrame

/** Server to client: this account muted or unmuted a conversation, on this device or another (decision 0042) */
@Serializable
@SerialName("mute")
data class MuteFrame(
    val conversationId: String,
    /** Whether the conversation is muted now */
    val muted: Boolean,
    /** When the mute ends, Unix milliseconds by the server's clock; absent while muted means until turned back on */
    val until: Long? = null,
) : WsFrame
