// Generated by tooling/ws-kotlin.mjs from api/openapi.json. Do not edit; run
// `node tooling/ws-kotlin.mjs` after `pnpm --dir backend openapi`.

package samtak.spjall.api

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Every frame on the WebSocket, tagged by `type` */
@Serializable
sealed interface WsFrame

/** Server to client, first frame on a new socket */
@Serializable
@SerialName("hello")
data class HelloFrame(
    /** Protocol version the server speaks */
    val protocol: Long,
    val serverTime: String,
) : WsFrame

/** Server to client: a conversation has messages up to `seq`; fetch them */
@Serializable
@SerialName("notify")
data class NotifyFrame(
    val conversationId: String,
    /** The newest sequence number in the conversation */
    val seq: Long,
) : WsFrame

/** Either direction; answered with `pong` */
@Serializable
@SerialName("ping")
data class PingFrame(
    val nonce: String? = null,
) : WsFrame

/** The answer to `ping`, echoing its nonce */
@Serializable
@SerialName("pong")
data class PongFrame(
    val nonce: String? = null,
) : WsFrame
