// @ts-check
// Emits the WebSocket frame union as a Kotlin sealed interface (decision 0005).
//
// openapi-generator's Kotlin output cannot decode a `oneOf` + discriminator
// union ("Serializer for subclass … not found in the polymorphic scope"), and
// the WS protocol is exactly that shape. So the Android side gets this small
// emitter instead: one `@Serializable sealed interface WsFrame`, one
// `@SerialName` class per member. kotlinx.serialization's default class
// discriminator is "type", which is the union's discriminator, so a plain
// `Json { ignoreUnknownKeys = true }` decodes it.
//
// `node tooling/ws-kotlin.mjs`          write the Kotlin file
// `node tooling/ws-kotlin.mjs --check`  fail when it is stale (CI, pre-push)
//
// Only the shapes listed in `kotlinType` are mapped. Anything else fails
// loudly, so a richer frame means extending this file, not a silent `Any`.

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { readJson, ROOT } from "./lib/repo.mjs";

const SPEC = "api/openapi.json";
export const OUTPUT = "api/kotlin/samtak/spjall/api/WsFrame.kt";
const UNION = "WsFrame";
const PACKAGE = "samtak.spjall.api";

// Hard keywords, which cannot name a property without backticks.
const KEYWORDS = new Set(
  "as break class continue do else false for fun if in interface is null object package return super this throw true try typealias typeof val var when while".split(
    " ",
  ),
);

/**
 * @param {any} schema a property schema
 * @param {string} where for the error message
 * @returns {string}
 */
function kotlinType(schema, where) {
  const scalar = { string: "String", integer: "Long", number: "Double", boolean: "Boolean" };
  if (schema.type === "array") return `List<${kotlinType(schema.items ?? {}, `${where}[]`)}>`;
  const type = scalar[/** @type {keyof typeof scalar} */ (schema.type)];
  if (!type || schema.format === "byte") {
    throw new Error(
      `${where}: unsupported schema ${JSON.stringify(schema)} (see tooling/ws-kotlin.mjs)`,
    );
  }
  return type;
}

/** @param {string | undefined} text @param {string} indent */
function doc(text, indent) {
  return text ? `${indent}/** ${text.replaceAll("*/", "*&#47;")} */\n` : "";
}

/**
 * @param {string} name component name
 * @param {any} schema the member's object schema
 * @param {string} tag the discriminator value it is mapped to
 */
function member(name, schema, tag) {
  const typeProp = schema.properties?.type;
  if (typeProp?.enum?.length !== 1 || typeProp.enum[0] !== tag) {
    throw new Error(`${name}: property "type" must be the literal "${tag}"`);
  }
  const required = new Set(schema.required ?? []);
  const fields = Object.entries(schema.properties)
    .filter(([key]) => key !== "type")
    .map(([key, prop]) => {
      if (!/^[a-z][A-Za-z0-9]*$/.test(key)) throw new Error(`${name}.${key}: not a camelCase name`);
      const id = KEYWORDS.has(key) ? `\`${key}\`` : key;
      const type = kotlinType(prop, `${name}.${key}`);
      const decl = required.has(key) ? `val ${id}: ${type}` : `val ${id}: ${type}? = null`;
      return `${doc(prop.description, "    ")}    ${decl},\n`;
    });
  const head = `${doc(schema.description, "")}@Serializable\n@SerialName("${tag}")\n`;
  if (fields.length === 0) return `${head}data object ${name} : ${UNION}\n`;
  return `${head}data class ${name}(\n${fields.join("")}) : ${UNION}\n`;
}

/**
 * @param {any} spec an OpenAPI 3.1 document
 * @returns {string} the Kotlin source
 */
export function emit(spec) {
  const schemas = spec.components?.schemas ?? {};
  const union = schemas[UNION];
  if (union?.discriminator?.propertyName !== "type" || !union.discriminator.mapping) {
    throw new Error(`${UNION}: needs a discriminator on "type" with a mapping`);
  }
  const members = Object.entries(union.discriminator.mapping).map(([tag, ref]) => {
    const name = String(ref).replace("#/components/schemas/", "");
    if (!schemas[name]) throw new Error(`${UNION}: mapping "${tag}" points at missing ${name}`);
    return member(name, schemas[name], tag);
  });
  return [
    `// Generated by tooling/ws-kotlin.mjs from ${SPEC}. Do not edit; run\n// \`node tooling/ws-kotlin.mjs\` after \`pnpm --filter spjall-backend openapi\`.\n`,
    `package ${PACKAGE}\n`,
    "import kotlinx.serialization.SerialName\nimport kotlinx.serialization.Serializable\n",
    `${doc(union.description, "")}@Serializable\nsealed interface ${UNION}\n`,
    ...members,
  ].join("\n");
}

function main() {
  const text = emit(readJson(SPEC));
  const path = join(ROOT, OUTPUT);
  if (!process.argv.includes("--check")) {
    writeFileSync(path, text);
    console.log(`wrote ${OUTPUT}`);
    return;
  }
  let committed = "";
  try {
    committed = readFileSync(path, "utf8");
  } catch {
    // Missing counts as stale.
  }
  if (committed !== text) {
    console.error(`❌ ${OUTPUT} is stale. Run \`node tooling/ws-kotlin.mjs\` and commit it.`);
    process.exit(1);
  }
  console.log(`✓ ${OUTPUT} matches ${SPEC}`);
}

if (import.meta.main) main();
